branch-defaults:
  default:
    environment: capstone-project
environment-defaults:
  capstone-project:
    branch: null
    repository: null
global:
  application_name: client
  default_ec2_keyname: null
  default_platform: Docker
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
