name: Deployment
on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  # deploy-backend:
  #   name: deploy REST API
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: dev
  #   strategy:
  #     matrix:
  #       node-version: [18.x]
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #   - name: Install Plugin and Deploy
  #     uses: serverless/github-action@v3
  #     with:
  #       args: -c "cd ./backend && rm -rf ./node-modules package-lock.json && npm cache clean --force && npm install --strict-ssl=false && npm audit fix | true && serverless plugin install --name serverless-iam-roles-per-function && serverless plugin install --name serverless-webpack && serverless plugin install --name serverless-plugin-tracing && serverless plugin install --name serverless-reqvalidator-plugin && serverless config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }} && export AWS_ACCESS_KEY_ID=AKIASDCI4QH764K5ELOI && export AWS_SECRET_ACCESS_KEY=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 && serverless deploy --verbose"
  #       entrypoint: /bin/sh
  #     env:
  #       SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
  #       SLS_DEBUG: 1
  client:
    name: Deploy Client
    runs-on: ubuntu-latest
    # env:
    #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #   AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install EB CLI
        run: |
          python -m pip install --upgrade pip
          pip install awsebcli
          
      - name: Generate deployment package
        run: |
          cd client
          npm install
          npm audit fix | true
          export SKIP_PREFLIGHT_CHECK=true
          export NODE_OPTIONS=--openssl-legacy-provider
          npm run build
          zip -r deploy.zip * .[^.]* -x "**node_modules**"
      - name: Deploy
        # run: |
        #   cd client
        #   eb init --platform node.js --region us-east-1
        #   eb terminate client --all --force

        # run: |
        #   cd client
        #   aws configure set aws_access_key_id "ASIASDCI4QH75AEHFTOU"
        #   aws configure set aws_secret_access_key "LzNBGYosHSOC/mzlVKRhS3AunXuR/bNc5g3OPfov"
        #   aws configure set aws_session_token "FwoGZXIvYXdzEIP//////////wEaDMec7lhbGDn8/6BNhiLVAefRefbUU+AIdCzPjvTwPgm1ArdqO6KBgDLXJcWXvmF3Q8TtTMEwDXd1yIx96c6clvtiW0qtBbY51lBLTJiQTzPDM4PXIjHnghh3falCuZCWAuM6IkcVGB7BlvXWBqL5Bb/BdVzPyoDZrve8vifExq8j7WSYWSTqJVWdPm+upEWjavLcOcHuBqCSTP5L97pJL15YWnBH9OshdFgznQ9FsE+akYeYwwyCmeqmLRMZI0z/MvOppEW3nFoo8IxNNVcWlwnQUn05qbz/1reOI7VckWGsz/xEhCiQtJakBjItLv96pGTR//XFNzcXYurWZLvyDZ7cwEy8QzMNAOJ2+XgQzakdTt/JXbPOSQJW"
        #   aws configure set default.region us-east-1
        #   export AWS_ACCESS_KEY_ID=ASIASDCI4QH75AEHFTOU
        #   export AWS_SECRET_ACCESS_KEY=LzNBGYosHSOC/mzlVKRhS3AunXuR/bNc5g3OPfov
        #   export AWS_SESSION_TOKEN=FwoGZXIvYXdzEIP//////////wEaDMec7lhbGDn8/6BNhiLVAefRefbUU+AIdCzPjvTwPgm1ArdqO6KBgDLXJcWXvmF3Q8TtTMEwDXd1yIx96c6clvtiW0qtBbY51lBLTJiQTzPDM4PXIjHnghh3falCuZCWAuM6IkcVGB7BlvXWBqL5Bb/BdVzPyoDZrve8vifExq8j7WSYWSTqJVWdPm+upEWjavLcOcHuBqCSTP5L97pJL15YWnBH9OshdFgznQ9FsE+akYeYwwyCmeqmLRMZI0z/MvOppEW3nFoo8IxNNVcWlwnQUn05qbz/1reOI7VckWGsz/xEhCiQtJakBjItLv96pGTR//XFNzcXYurWZLvyDZ7cwEy8QzMNAOJ2+XgQzakdTt/JXbPOSQJW
        #   eb init --platform node.js --region us-east-1
        #   eb create capstone-project --enable-spot --instance-types "t3.large"

        run: |
          cd client
          aws configure set aws_access_key_id "ASIASDCI4QH75AEHFTOU"
          aws configure set aws_secret_access_key "LzNBGYosHSOC/mzlVKRhS3AunXuR/bNc5g3OPfov"
          aws configure set aws_session_token "FwoGZXIvYXdzEIP//////////wEaDMec7lhbGDn8/6BNhiLVAefRefbUU+AIdCzPjvTwPgm1ArdqO6KBgDLXJcWXvmF3Q8TtTMEwDXd1yIx96c6clvtiW0qtBbY51lBLTJiQTzPDM4PXIjHnghh3falCuZCWAuM6IkcVGB7BlvXWBqL5Bb/BdVzPyoDZrve8vifExq8j7WSYWSTqJVWdPm+upEWjavLcOcHuBqCSTP5L97pJL15YWnBH9OshdFgznQ9FsE+akYeYwwyCmeqmLRMZI0z/MvOppEW3nFoo8IxNNVcWlwnQUn05qbz/1reOI7VckWGsz/xEhCiQtJakBjItLv96pGTR//XFNzcXYurWZLvyDZ7cwEy8QzMNAOJ2+XgQzakdTt/JXbPOSQJW"
          aws configure set default.region us-east-1
          export AWS_ACCESS_KEY_ID=ASIASDCI4QH75AEHFTOU
          export AWS_SECRET_ACCESS_KEY=LzNBGYosHSOC/mzlVKRhS3AunXuR/bNc5g3OPfov
          export AWS_SESSION_TOKEN=FwoGZXIvYXdzEIP//////////wEaDMec7lhbGDn8/6BNhiLVAefRefbUU+AIdCzPjvTwPgm1ArdqO6KBgDLXJcWXvmF3Q8TtTMEwDXd1yIx96c6clvtiW0qtBbY51lBLTJiQTzPDM4PXIjHnghh3falCuZCWAuM6IkcVGB7BlvXWBqL5Bb/BdVzPyoDZrve8vifExq8j7WSYWSTqJVWdPm+upEWjavLcOcHuBqCSTP5L97pJL15YWnBH9OshdFgznQ9FsE+akYeYwwyCmeqmLRMZI0z/MvOppEW3nFoo8IxNNVcWlwnQUn05qbz/1reOI7VckWGsz/xEhCiQtJakBjItLv96pGTR//XFNzcXYurWZLvyDZ7cwEy8QzMNAOJ2+XgQzakdTt/JXbPOSQJW
          eb init --platform node.js --region us-east-1
          eb deploy

  